import type { Module } from '../../types'

export const basics: Module = {
  id: 'basics',
  order: 1,
  title: 'Основы',
  emoji: '🌱',
  summary: 'Переменные, числа, строки и первые функции. С чего начинается любой код.',
  tasks: [
    {
      id: 'basics-01',
      moduleId: 'basics',
      title: 'Привет, мир!',
      kind: 'js',
      difficulty: 1,
      xp: 10,
      prompt:
        'Верни из функции `greet` строку `Привет, мир!` (ровно так, с восклицательным знаком).',
      hints: ['Строки пишутся в кавычках: `\'текст\'`.', 'Используй `return`.'],
      starter: 'function greet() {\n  // верни строку\n}\n',
      solution: "function greet() {\n  return 'Привет, мир!'\n}\n",
      fn: 'greet',
      cases: [{ name: 'возвращает приветствие', args: [], expected: 'Привет, мир!' }],
    },
    {
      id: 'basics-02',
      moduleId: 'basics',
      title: 'Сумма двух чисел',
      kind: 'js',
      difficulty: 1,
      xp: 10,
      prompt: 'Функция `add(a, b)` должна вернуть сумму двух чисел.',
      hints: ['Сложение — это `+`.'],
      starter: 'function add(a, b) {\n  \n}\n',
      solution: 'function add(a, b) {\n  return a + b\n}\n',
      fn: 'add',
      cases: [
        { name: '2 + 3 = 5', args: [2, 3], expected: 5 },
        { name: '-1 + 1 = 0', args: [-1, 1], expected: 0 },
        { name: '100 + 250 = 350', args: [100, 250], expected: 350 },
      ],
    },
    {
      id: 'basics-03',
      moduleId: 'basics',
      title: 'Разность',
      kind: 'js',
      difficulty: 1,
      xp: 10,
      prompt: 'Функция `subtract(a, b)` возвращает разность `a - b`.',
      hints: ['Вычитание — это `-`.'],
      starter: 'function subtract(a, b) {\n  \n}\n',
      solution: 'function subtract(a, b) {\n  return a - b\n}\n',
      fn: 'subtract',
      cases: [
        { name: '10 - 4 = 6', args: [10, 4], expected: 6 },
        { name: '3 - 8 = -5', args: [3, 8], expected: -5 },
      ],
    },
    {
      id: 'basics-04',
      moduleId: 'basics',
      title: 'Площадь прямоугольника',
      kind: 'js',
      difficulty: 1,
      xp: 15,
      prompt: 'Функция `area(width, height)` возвращает площадь прямоугольника.',
      hints: ['Площадь = ширина × высота.', 'Умножение — это `*`.'],
      starter: 'function area(width, height) {\n  \n}\n',
      solution: 'function area(width, height) {\n  return width * height\n}\n',
      fn: 'area',
      cases: [
        { name: '3 × 4 = 12', args: [3, 4], expected: 12 },
        { name: '5 × 5 = 25', args: [5, 5], expected: 25 },
      ],
    },
    {
      id: 'basics-05',
      moduleId: 'basics',
      title: 'Периметр квадрата',
      kind: 'js',
      difficulty: 1,
      xp: 15,
      prompt: 'Функция `perimeter(side)` возвращает периметр квадрата со стороной `side`.',
      hints: ['У квадрата 4 равные стороны.'],
      starter: 'function perimeter(side) {\n  \n}\n',
      solution: 'function perimeter(side) {\n  return side * 4\n}\n',
      fn: 'perimeter',
      cases: [
        { name: 'сторона 2 → 8', args: [2], expected: 8 },
        { name: 'сторона 7 → 28', args: [7], expected: 28 },
      ],
    },
    {
      id: 'basics-06',
      moduleId: 'basics',
      title: 'Среднее двух чисел',
      kind: 'js',
      difficulty: 2,
      xp: 15,
      prompt: 'Функция `average(a, b)` возвращает среднее арифметическое двух чисел.',
      hints: ['Сложи и раздели на 2.', 'Деление — это `/`.'],
      starter: 'function average(a, b) {\n  \n}\n',
      solution: 'function average(a, b) {\n  return (a + b) / 2\n}\n',
      fn: 'average',
      cases: [
        { name: '(4 + 6) / 2 = 5', args: [4, 6], expected: 5 },
        { name: '(3 + 4) / 2 = 3.5', args: [3, 4], expected: 3.5 },
      ],
    },
    {
      id: 'basics-07',
      moduleId: 'basics',
      title: 'Число в строку',
      kind: 'js',
      difficulty: 2,
      xp: 15,
      prompt:
        'Функция `toText(n)` превращает число в строку и добавляет к нему ` руб.`. Например, `199` → `199 руб.`',
      hints: ['Шаблонные строки: `` `${n} руб.` ``.'],
      starter: 'function toText(n) {\n  \n}\n',
      solution: 'function toText(n) {\n  return `${n} руб.`\n}\n',
      fn: 'toText',
      cases: [
        { name: '199 → "199 руб."', args: [199], expected: '199 руб.' },
        { name: '0 → "0 руб."', args: [0], expected: '0 руб.' },
      ],
    },
    {
      id: 'basics-08',
      moduleId: 'basics',
      title: 'Логическое НЕ',
      kind: 'js',
      difficulty: 2,
      xp: 15,
      prompt: 'Функция `negate(value)` возвращает противоположное булево значение.',
      hints: ['Оператор `!` инвертирует булево значение.'],
      starter: 'function negate(value) {\n  \n}\n',
      solution: 'function negate(value) {\n  return !value\n}\n',
      fn: 'negate',
      cases: [
        { name: '!true = false', args: [true], expected: false },
        { name: '!false = true', args: [false], expected: true },
      ],
    },
    {
      id: 'basics-09',
      moduleId: 'basics',
      title: 'Чётное число?',
      kind: 'js',
      difficulty: 2,
      xp: 20,
      prompt: 'Функция `isEven(n)` возвращает `true`, если число чётное, иначе `false`.',
      hints: ['Остаток от деления — оператор `%`.', 'Чётное число делится на 2 без остатка.'],
      starter: 'function isEven(n) {\n  \n}\n',
      solution: 'function isEven(n) {\n  return n % 2 === 0\n}\n',
      fn: 'isEven',
      cases: [
        { name: '4 чётное', args: [4], expected: true },
        { name: '7 нечётное', args: [7], expected: false },
        { name: '0 чётное', args: [0], expected: true },
      ],
    },
    {
      id: 'basics-10',
      moduleId: 'basics',
      title: 'Максимум из двух',
      kind: 'js',
      difficulty: 2,
      xp: 20,
      prompt: 'Функция `max2(a, b)` возвращает большее из двух чисел.',
      hints: ['Можно через `if`, а можно через `Math.max`.'],
      starter: 'function max2(a, b) {\n  \n}\n',
      solution: 'function max2(a, b) {\n  return Math.max(a, b)\n}\n',
      fn: 'max2',
      cases: [
        { name: 'max(3, 9) = 9', args: [3, 9], expected: 9 },
        { name: 'max(-2, -5) = -2', args: [-2, -5], expected: -2 },
        { name: 'max(4, 4) = 4', args: [4, 4], expected: 4 },
      ],
    },
    {
      id: 'basics-11',
      moduleId: 'basics',
      title: 'Секунды в формат M:SS',
      kind: 'js',
      difficulty: 3,
      xp: 25,
      prompt:
        'Функция `formatTime(totalSeconds)` возвращает строку вида `M:SS`. Например, `75` → `1:15`, а `5` → `0:05` (секунды всегда двузначные).',
      hints: [
        'Минуты: `Math.floor(totalSeconds / 60)`.',
        'Секунды: `totalSeconds % 60`.',
        'Двузначные секунды: `String(sec).padStart(2, \'0\')`.',
      ],
      starter: 'function formatTime(totalSeconds) {\n  \n}\n',
      solution:
        "function formatTime(totalSeconds) {\n  const min = Math.floor(totalSeconds / 60)\n  const sec = totalSeconds % 60\n  return `${min}:${String(sec).padStart(2, '0')}`\n}\n",
      fn: 'formatTime',
      cases: [
        { name: '75 → "1:15"', args: [75], expected: '1:15' },
        { name: '5 → "0:05"', args: [5], expected: '0:05' },
        { name: '600 → "10:00"', args: [600], expected: '10:00' },
      ],
    },
    {
      id: 'basics-12',
      moduleId: 'basics',
      title: 'Фаренгейты в Цельсии',
      kind: 'js',
      difficulty: 3,
      xp: 25,
      prompt:
        'Функция `toCelsius(f)` переводит температуру из Фаренгейтов в Цельсии по формуле `(F − 32) × 5 / 9`.',
      hints: ['Следи за порядком действий — скобки важны.'],
      starter: 'function toCelsius(f) {\n  \n}\n',
      solution: 'function toCelsius(f) {\n  return (f - 32) * 5 / 9\n}\n',
      fn: 'toCelsius',
      cases: [
        { name: '32°F = 0°C', args: [32], expected: 0, matcher: 'approx' },
        { name: '212°F = 100°C', args: [212], expected: 100, matcher: 'approx' },
        { name: '98.6°F ≈ 37°C', args: [98.6], expected: 37, matcher: 'approx' },
      ],
    },
  ],
}
