import type { Module } from '../../types'

export const operators: Module = {
  id: 'operators',
  order: 2,
  title: 'Операторы и условия',
  emoji: '➗',
  summary: 'Сравнения, логика и ветвление: if / else, тернарный оператор, switch, min/max и оценки.',
  tasks: [
    {
      id: 'operators-01',
      moduleId: 'operators',
      title: 'Больше?',
      kind: 'js',
      difficulty: 1,
      xp: 10,
      prompt:
        'Функция `isBigger(a, b)` возвращает `true`, если `a` больше `b`, иначе `false`.',
      hints: ['Сравнение «больше» — это оператор `>`.', 'Результат сравнения уже булев — его можно сразу вернуть.'],
      starter: 'function isBigger(a, b) {\n  \n}\n',
      solution: 'function isBigger(a, b) {\n  return a > b\n}\n',
      fn: 'isBigger',
      cases: [
        { name: '5 > 3 → true', args: [5, 3], expected: true },
        { name: '2 > 8 → false', args: [2, 8], expected: false },
        { name: '4 > 4 → false', args: [4, 4], expected: false },
      ],
    },
    {
      id: 'operators-02',
      moduleId: 'operators',
      title: 'Равны ли строго?',
      kind: 'js',
      difficulty: 1,
      xp: 10,
      prompt:
        'Функция `sameValue(a, b)` возвращает `true`, если значения строго равны (тип и значение совпадают), иначе `false`.',
      hints: ['Строгое равенство — оператор `===` (три знака равно).', '`===` не приводит типы: `1 === "1"` это `false`.'],
      starter: 'function sameValue(a, b) {\n  \n}\n',
      solution: 'function sameValue(a, b) {\n  return a === b\n}\n',
      fn: 'sameValue',
      cases: [
        { name: '5 === 5 → true', args: [5, 5], expected: true },
        { name: '1 === "1" → false', args: [1, '1'], expected: false },
        { name: '"js" === "js" → true', args: ['js', 'js'], expected: true },
      ],
    },
    {
      id: 'operators-03',
      moduleId: 'operators',
      title: 'Совершеннолетний?',
      kind: 'js',
      difficulty: 1,
      xp: 15,
      prompt:
        'Функция `canVote(age)` через `if / else` возвращает строку `Можно`, если возраст 18 или больше, иначе `Рано`.',
      hints: ['Условие: `if (age >= 18) { ... } else { ... }`.', '«Больше или равно» — это `>=`.'],
      starter: 'function canVote(age) {\n  \n}\n',
      solution:
        "function canVote(age) {\n  if (age >= 18) {\n    return 'Можно'\n  } else {\n    return 'Рано'\n  }\n}\n",
      fn: 'canVote',
      cases: [
        { name: '20 → "Можно"', args: [20], expected: 'Можно' },
        { name: '18 → "Можно"', args: [18], expected: 'Можно' },
        { name: '15 → "Рано"', args: [15], expected: 'Рано' },
      ],
    },
    {
      id: 'operators-04',
      moduleId: 'operators',
      title: 'Тернарный: чётное или нечётное',
      kind: 'js',
      difficulty: 2,
      xp: 15,
      prompt:
        'Используя тернарный оператор, функция `parity(n)` возвращает `Чёт`, если число чётное, иначе `Нечёт`.',
      hints: ['Тернарный оператор: `условие ? еслиДа : еслиНет`.', 'Чётность: `n % 2 === 0`.'],
      starter: 'function parity(n) {\n  \n}\n',
      solution: "function parity(n) {\n  return n % 2 === 0 ? 'Чёт' : 'Нечёт'\n}\n",
      fn: 'parity',
      cases: [
        { name: '4 → "Чёт"', args: [4], expected: 'Чёт' },
        { name: '7 → "Нечёт"', args: [7], expected: 'Нечёт' },
        { name: '0 → "Чёт"', args: [0], expected: 'Чёт' },
      ],
    },
    {
      id: 'operators-05',
      moduleId: 'operators',
      title: 'Знак числа',
      kind: 'js',
      difficulty: 2,
      xp: 20,
      prompt:
        'Функция `sign(n)` возвращает `1`, если число положительное, `-1`, если отрицательное, и `0`, если равно нулю.',
      hints: ['Тут три случая — пригодится `if ... else if ... else`.', 'Сначала проверь `n > 0`, потом `n < 0`, иначе `0`.'],
      starter: 'function sign(n) {\n  \n}\n',
      solution:
        'function sign(n) {\n  if (n > 0) {\n    return 1\n  } else if (n < 0) {\n    return -1\n  } else {\n    return 0\n  }\n}\n',
      fn: 'sign',
      cases: [
        { name: '5 → 1', args: [5], expected: 1 },
        { name: '-3 → -1', args: [-3], expected: -1 },
        { name: '0 → 0', args: [0], expected: 0 },
      ],
    },
    {
      id: 'operators-06',
      moduleId: 'operators',
      title: 'Попадает в диапазон?',
      kind: 'js',
      difficulty: 2,
      xp: 20,
      prompt:
        'Функция `inRange(n)` возвращает `true`, если число от 1 до 10 включительно, иначе `false`. Используй логическое И.',
      hints: ['Логическое И — оператор `&&`.', 'Нужно, чтобы выполнялись оба условия: `n >= 1` И `n <= 10`.'],
      starter: 'function inRange(n) {\n  \n}\n',
      solution: 'function inRange(n) {\n  return n >= 1 && n <= 10\n}\n',
      fn: 'inRange',
      cases: [
        { name: '5 → true', args: [5], expected: true },
        { name: '10 → true', args: [10], expected: true },
        { name: '0 → false', args: [0], expected: false },
        { name: '11 → false', args: [11], expected: false },
      ],
    },
    {
      id: 'operators-07',
      moduleId: 'operators',
      title: 'Выходной день?',
      kind: 'js',
      difficulty: 2,
      xp: 20,
      prompt:
        'Функция `isWeekend(day)` получает номер дня недели (1 — понедельник … 7 — воскресенье) и возвращает `true`, если это суббота (6) или воскресенье (7). Используй логическое ИЛИ.',
      hints: ['Логическое ИЛИ — оператор `||`.', 'Достаточно одного из условий: `day === 6` ИЛИ `day === 7`.'],
      starter: 'function isWeekend(day) {\n  \n}\n',
      solution: 'function isWeekend(day) {\n  return day === 6 || day === 7\n}\n',
      fn: 'isWeekend',
      cases: [
        { name: '6 → true', args: [6], expected: true },
        { name: '7 → true', args: [7], expected: true },
        { name: '3 → false', args: [3], expected: false },
      ],
    },
    {
      id: 'operators-08',
      moduleId: 'operators',
      title: 'switch: название цвета',
      kind: 'js',
      difficulty: 3,
      xp: 25,
      prompt:
        'Функция `colorName(code)` через `switch` возвращает название цвета: `R` → `красный`, `G` → `зелёный`, `B` → `синий`. Для любого другого кода верни `неизвестно`.',
      hints: [
        'Каркас: `switch (code) { case \'R\': ...; default: ... }`.',
        'Не забывай `return` (или `break`) в каждой ветке.',
        'Ветка `default` ловит все остальные значения.',
      ],
      starter: 'function colorName(code) {\n  \n}\n',
      solution:
        "function colorName(code) {\n  switch (code) {\n    case 'R':\n      return 'красный'\n    case 'G':\n      return 'зелёный'\n    case 'B':\n      return 'синий'\n    default:\n      return 'неизвестно'\n  }\n}\n",
      fn: 'colorName',
      cases: [
        { name: '"R" → "красный"', args: ['R'], expected: 'красный' },
        { name: '"G" → "зелёный"', args: ['G'], expected: 'зелёный' },
        { name: '"B" → "синий"', args: ['B'], expected: 'синий' },
        { name: '"X" → "неизвестно"', args: ['X'], expected: 'неизвестно' },
      ],
    },
    {
      id: 'operators-09',
      moduleId: 'operators',
      title: 'Ограничить диапазон (clamp)',
      kind: 'js',
      difficulty: 3,
      xp: 25,
      prompt:
        'Функция `clamp(n, min, max)` возвращает число `n`, «зажатое» в диапазон: если `n` меньше `min` — вернёт `min`, если больше `max` — вернёт `max`, иначе само `n`.',
      hints: [
        'Сначала обработай случай `n < min`, потом `n > max`.',
        'Короткий способ: `Math.max(min, Math.min(n, max))`.',
      ],
      starter: 'function clamp(n, min, max) {\n  \n}\n',
      solution:
        'function clamp(n, min, max) {\n  if (n < min) {\n    return min\n  }\n  if (n > max) {\n    return max\n  }\n  return n\n}\n',
      fn: 'clamp',
      cases: [
        { name: 'clamp(5, 0, 10) → 5', args: [5, 0, 10], expected: 5 },
        { name: 'clamp(-3, 0, 10) → 0', args: [-3, 0, 10], expected: 0 },
        { name: 'clamp(42, 0, 10) → 10', args: [42, 0, 10], expected: 10 },
        { name: 'clamp(10, 0, 10) → 10', args: [10, 0, 10], expected: 10 },
      ],
    },
    {
      id: 'operators-10',
      moduleId: 'operators',
      title: 'Оценка по баллам',
      kind: 'js',
      difficulty: 4,
      xp: 30,
      prompt:
        'Функция `grade(score)` ставит оценку по баллам (0–100): 90 и выше → `5`, 75–89 → `4`, 60–74 → `3`, меньше 60 → `2`. Верни число-оценку.',
      hints: [
        'Проверяй пороги сверху вниз: сначала самый высокий.',
        'Цепочка `if (score >= 90) ... else if (score >= 75) ...`.',
        'Когда проверяешь по убыванию, второе условие уже значит «меньше 90».',
      ],
      starter: 'function grade(score) {\n  \n}\n',
      solution:
        'function grade(score) {\n  if (score >= 90) {\n    return 5\n  } else if (score >= 75) {\n    return 4\n  } else if (score >= 60) {\n    return 3\n  } else {\n    return 2\n  }\n}\n',
      fn: 'grade',
      cases: [
        { name: '95 → 5', args: [95], expected: 5 },
        { name: '80 → 4', args: [80], expected: 4 },
        { name: '60 → 3', args: [60], expected: 3 },
        { name: '40 → 2', args: [40], expected: 2 },
      ],
    },
  ],
}
