import type { Module } from '../../types'

export const strings: Module = {
  id: 'strings',
  order: 3,
  title: 'Строки',
  emoji: '🔤',
  summary: 'Длина, регистр, поиск, срезы и преобразования текста. Учимся управлять строками.',
  tasks: [
    {
      id: 'strings-01',
      moduleId: 'strings',
      title: 'Длина строки',
      kind: 'js',
      difficulty: 1,
      xp: 10,
      prompt: 'Функция `len(text)` должна вернуть количество символов в строке.',
      hints: ['У строк есть свойство `.length`.', 'Это не метод — скобки не нужны: `text.length`.'],
      starter: 'function len(text) {\n  \n}\n',
      solution: 'function len(text) {\n  return text.length\n}\n',
      fn: 'len',
      cases: [
        { name: '"кот" → 3', args: ['кот'], expected: 3 },
        { name: '"" → 0', args: [''], expected: 0 },
        { name: '"JavaScript" → 10', args: ['JavaScript'], expected: 10 },
      ],
    },
    {
      id: 'strings-02',
      moduleId: 'strings',
      title: 'Кричим капсом',
      kind: 'js',
      difficulty: 1,
      xp: 10,
      prompt:
        'Функция `shout(text)` возвращает строку в ВЕРХНЕМ регистре. Например, `привет` → `ПРИВЕТ`. (Родственный метод `.toLowerCase()` делает наоборот — строчными.)',
      hints: ['Есть метод `.toUpperCase()`.', 'Не забудь круглые скобки: `text.toUpperCase()`.'],
      starter: 'function shout(text) {\n  \n}\n',
      solution: 'function shout(text) {\n  return text.toUpperCase()\n}\n',
      fn: 'shout',
      cases: [
        { name: '"привет" → "ПРИВЕТ"', args: ['привет'], expected: 'ПРИВЕТ' },
        { name: '"Hello" → "HELLO"', args: ['Hello'], expected: 'HELLO' },
      ],
    },
    {
      id: 'strings-03',
      moduleId: 'strings',
      title: 'Есть ли слово?',
      kind: 'js',
      difficulty: 2,
      xp: 15,
      prompt:
        'Функция `hasWord(text, word)` возвращает `true`, если строка `text` содержит подстроку `word`, иначе `false`.',
      hints: [
        'Есть метод `.includes(...)`.',
        '`text.includes(word)` сразу возвращает булево значение.',
      ],
      starter: 'function hasWord(text, word) {\n  \n}\n',
      solution: 'function hasWord(text, word) {\n  return text.includes(word)\n}\n',
      fn: 'hasWord',
      cases: [
        { name: '"кошка" содержит "шка"', args: ['кошка', 'шка'], expected: true },
        { name: '"кошка" не содержит "пёс"', args: ['кошка', 'пёс'], expected: false },
        { name: '"hello world" содержит "world"', args: ['hello world', 'world'], expected: true },
      ],
    },
    {
      id: 'strings-04',
      moduleId: 'strings',
      title: 'Где буква?',
      kind: 'js',
      difficulty: 2,
      xp: 15,
      prompt:
        'Функция `find(text, ch)` возвращает индекс первого вхождения символа `ch` в строку `text`. Если символа нет — верни `-1`.',
      hints: [
        'Есть метод `.indexOf(...)`.',
        '`.indexOf` сам возвращает `-1`, если ничего не нашёл.',
      ],
      starter: 'function find(text, ch) {\n  \n}\n',
      solution: 'function find(text, ch) {\n  return text.indexOf(ch)\n}\n',
      fn: 'find',
      cases: [
        { name: 'первый символ имеет индекс 0', args: ['кот', 'к'], expected: 0 },
        { name: '"кот" — "т" на индексе 2', args: ['кот', 'т'], expected: 2 },
        { name: 'нет символа → -1', args: ['кот', 'я'], expected: -1 },
      ],
    },
    {
      id: 'strings-05',
      moduleId: 'strings',
      title: 'Первые три буквы',
      kind: 'js',
      difficulty: 2,
      xp: 20,
      prompt:
        'Функция `first3(text)` возвращает первые три символа строки. Если строка короче — верни её целиком.',
      hints: [
        'Есть метод `.slice(начало, конец)` (похожий метод — `.substring`).',
        '`text.slice(0, 3)` берёт символы с 0 по 3 (не включая 3).',
        'Если строка короче трёх символов, `.slice` сам вернёт что есть.',
      ],
      starter: 'function first3(text) {\n  \n}\n',
      solution: 'function first3(text) {\n  return text.slice(0, 3)\n}\n',
      fn: 'first3',
      cases: [
        { name: '"котёнок" → "кот"', args: ['котёнок'], expected: 'кот' },
        { name: '"да" → "да"', args: ['да'], expected: 'да' },
        { name: '"JavaScript" → "Jav"', args: ['JavaScript'], expected: 'Jav' },
      ],
    },
    {
      id: 'strings-06',
      moduleId: 'strings',
      title: 'Слова через дефис',
      kind: 'js',
      difficulty: 3,
      xp: 20,
      prompt:
        'Функция `dashify(sentence)` разбивает предложение на слова по пробелам и склеивает их обратно через дефис. Например, `я люблю код` → `я-люблю-код`.',
      hints: [
        'Разбей строку методом `.split(\' \')` — получится массив слов.',
        'Склей массив обратно методом `.join(\'-\')`.',
      ],
      starter: 'function dashify(sentence) {\n  \n}\n',
      solution: "function dashify(sentence) {\n  return sentence.split(' ').join('-')\n}\n",
      fn: 'dashify',
      cases: [
        { name: '"я люблю код" → "я-люблю-код"', args: ['я люблю код'], expected: 'я-люблю-код' },
        { name: '"hello world" → "hello-world"', args: ['hello world'], expected: 'hello-world' },
        { name: 'одно слово без дефиса', args: ['кот'], expected: 'кот' },
      ],
    },
    {
      id: 'strings-07',
      moduleId: 'strings',
      title: 'Разворот строки',
      kind: 'js',
      difficulty: 3,
      xp: 25,
      prompt: 'Функция `reverse(text)` возвращает строку задом наперёд. Например, `кот` → `ток`.',
      hints: [
        'Строку можно превратить в массив символов через `.split(\'\')`.',
        'У массива есть метод `.reverse()`.',
        'Обратно в строку — `.join(\'\')`.',
      ],
      starter: 'function reverse(text) {\n  \n}\n',
      solution: "function reverse(text) {\n  return text.split('').reverse().join('')\n}\n",
      fn: 'reverse',
      cases: [
        { name: '"кот" → "ток"', args: ['кот'], expected: 'ток' },
        { name: '"abc" → "cba"', args: ['abc'], expected: 'cba' },
        { name: '"" → ""', args: [''], expected: '' },
      ],
    },
    {
      id: 'strings-08',
      moduleId: 'strings',
      title: 'Считаем букву',
      kind: 'js',
      difficulty: 3,
      xp: 25,
      prompt:
        'Функция `countChar(text, ch)` считает, сколько раз символ `ch` встречается в строке `text`.',
      hints: [
        'Раздели строку по символу: `text.split(ch)`.',
        'Кусочков получится на один больше, чем самих символов. Значит, ответ — `text.split(ch).length - 1`.',
        'Или пройди по строке циклом и считай совпадения.',
      ],
      starter: 'function countChar(text, ch) {\n  \n}\n',
      solution: 'function countChar(text, ch) {\n  return text.split(ch).length - 1\n}\n',
      fn: 'countChar',
      cases: [
        { name: 'в "мама" две "а"', args: ['мама', 'а'], expected: 2 },
        { name: 'в "балалайка" четыре "а"', args: ['балалайка', 'а'], expected: 4 },
        { name: 'нет символа → 0', args: ['кот', 'я'], expected: 0 },
      ],
    },
    {
      id: 'strings-09',
      moduleId: 'strings',
      title: 'Заглавная буква',
      kind: 'js',
      difficulty: 4,
      xp: 30,
      prompt:
        'Функция `capitalize(text)` делает первую букву заглавной, а остальные — строчными. Лишние пробелы по краям убираем. Например, `  пРИвет ` → `Привет`.',
      hints: [
        'Сначала убери пробелы по краям методом `.trim()`.',
        'Первый символ: `text[0].toUpperCase()`.',
        'Остаток строки в нижнем регистре: `text.slice(1).toLowerCase()`. Склей их через `+`.',
      ],
      starter: 'function capitalize(text) {\n  \n}\n',
      solution:
        "function capitalize(text) {\n  const t = text.trim()\n  if (t.length === 0) return ''\n  return t[0].toUpperCase() + t.slice(1).toLowerCase()\n}\n",
      fn: 'capitalize',
      cases: [
        { name: '"пРИвет" → "Привет"', args: ['пРИвет'], expected: 'Привет' },
        { name: 'обрезает пробелы: "  hello " → "Hello"', args: ['  hello '], expected: 'Hello' },
        { name: '"" → ""', args: [''], expected: '' },
      ],
    },
    {
      id: 'strings-10',
      moduleId: 'strings',
      title: 'Цензура',
      kind: 'js',
      difficulty: 4,
      xp: 30,
      prompt:
        'Функция `censor(text, bad)` заменяет ВСЕ вхождения слова `bad` на `***` и убирает лишние пробелы по краям строки. Например, `  ты бяка бяка ` со словом `бяка` → `ты *** ***`.',
      hints: [
        'Сначала уберём пробелы по краям: `text.trim()`.',
        'Заменить сразу все вхождения помогает метод `.replaceAll(что, наЧто)`.',
        'Собери всё в цепочку: `text.trim().replaceAll(bad, \'***\')`.',
      ],
      starter: 'function censor(text, bad) {\n  \n}\n',
      solution:
        "function censor(text, bad) {\n  return text.trim().replaceAll(bad, '***')\n}\n",
      fn: 'censor',
      cases: [
        {
          name: 'заменяет оба "бяка"',
          args: ['  ты бяка бяка ', 'бяка'],
          expected: 'ты *** ***',
        },
        { name: 'нет плохого слова — только trim', args: ['  привет ', 'зло'], expected: 'привет' },
        { name: 'заменяет три вхождения', args: ['ааа', 'а'], expected: '*********' },
      ],
    },
  ],
}
